services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nuxt-base
    container_name: nuxt-base
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
      NUXT_PUBLIC_APP_NAME: ${NUXT_PUBLIC_APP_NAME}
      NUXT_GEMINI_API_KEY: ${NUXT_GEMINI_API_KEY}
      NUXT_API_SECRET: ${NUXT_API_SECRET}
    env_file:
      - .env
